Org branch
Zummit-Africa-Inc/zapi-dummy-core pull request #19
Opened 2022-06-13 11:18 UTC by DorcasOJ

- created create-organisation post request
- created create-users post request
- created get-organisation-by-id get request
- created get-users-by-id get request

2022-06-13 11:36 UTC, PhilemonBrain requested changes

2022-06-13 11:36 UTC, PhilemonBrain commented on src/organisation/organisation.service.ts
> +      const mail_extension = profile.email.substring(
why are u still adding this mail_extension stuff, what is it for?

2022-06-13 11:36 UTC, PhilemonBrain commented on src/organisation/organisation.service.ts
> +      const profile = await this.profileRepo.findOne(profileId);
what if the id is not correct?

2022-06-13 11:36 UTC, PhilemonBrain commented on src/organisation/organisation.service.ts
> +            'Non-existing Values',
"Non-existing values".... change it

2022-06-13 11:36 UTC, PhilemonBrain commented on src/organisation/organisation.service.ts
> +          ZapiResponse.BadRequest(
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

check and use the corresponding status headers, like 'Not Found' and 'Unauthorized '

2022-06-13 11:36 UTC, PhilemonBrain commented
enusre to fix the conflicts as well @DorcasOJ

2022-06-13 11:53 UTC, Chimexx requested changes
Why 2 migration files? If you need to generate another file, revert the previous one then create a new one. I think each PR should have all entity changes in one migration file.

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/dto/create-user.dto.ts
> +    default: OrgRole.DEVELOPER,
I'm not sure about this, But are you supposed to pass in these values in a dto file?

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.controller.ts
> +    return ZapiResponse.Ok(allOrganisation, 'All Organisation', '200');
Please fix the typo...

line 42  Get one organisation
line 45 You are getting one organisation right? so why all org.?

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +// import { ProfileDto } from 'src/organisation/dto/profile-dto';
Remove unused code

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +        price_per_month: 0,
Why dont you just set a default value of 0 in the entity, then remove this from the dto.

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +      });
This works, but it's better to find with id

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +        where: { profile: profile, organisation: organisation },
Are you supposed to be using the found profile or just the id?

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +      const existingUser = await this.profileOrgRepo.findOne({
I think this should come at the beginning of the function, to prevent the rest of the code from running if the user exists

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +        profile: profile,
Again, this should be profile.id and organisation.id.
Hope you tested the code.

2022-06-13 11:53 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +  }
What if the supplied id was wrong? or not found?
Use custom response object here

2022-06-13 12:27 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +      const mail_extension = profile.email.substring(
You told me I can leave that but should remove the price column for now.
But I'll remove that too.

2022-06-13 12:34 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +            'Non-existing Values',
okay

2022-06-13 13:03 UTC, DorcasOJ commented on src/organisation/dto/create-user.dto.ts
> +    default: OrgRole.DEVELOPER,
https://docs.nestjs.com/openapi/types-and-parameters#enums

2022-06-13 13:09 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +        price_per_month: 0,
That means I would have to create another migration file, besides we might decide to expand on this column later.

2022-06-13 13:16 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +        price_per_month: 0,
what do you think?

2022-06-13 13:18 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +        where: { profile: profile, organisation: organisation },
The found profile, you'll get an error if you use just the id

2022-06-13 13:20 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +      const existingUser = await this.profileOrgRepo.findOne({
It is at the beginning, I needed to get profile and organisation before checking if it exist in the profileOrg table

2022-06-13 13:22 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +        profile: profile,
yes, I tested. 
Try it, you'll get an error if you specify only the id

2022-06-13 13:26 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +  }
okay

2022-06-14 13:01 UTC, Chimexx requested changes

2022-06-14 13:01 UTC, Chimexx commented on src/organisation/organisation.service.ts
>      return await this.orgRepo.findOne(id);
Use custom response object

2022-06-14 13:01 UTC, Chimexx commented on src/organisation/organisation.service.ts
>      return await this.orgRepo.find();
Use custom response object

2022-06-14 13:13 UTC, andyjrII requested changes

2022-06-14 13:13 UTC, andyjrII commented on src/organisation/organisation.controller.ts
> +  }
Also, your endpoint payload should include the organization for which the user is to be added to. 

Your endpoint only accepts the email of the user that created the organization & adds that user with the email to the organization & then does not update the organizationId under the profile-org table

2022-06-14 13:48 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +}
Users of the organisation are in the profile-org table in relation to the organisation id

2022-06-14 15:01 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
The id that should be received from the param is the organisation id.  all 'id' in organisation.controller refers to organisationId, every other id was specified, eg profileId

2022-06-14 15:56 UTC, andyjrII commented on src/organisation/organisation.controller.ts
> +  }
That means the endpoint isn't working as expected because I used the user Id to add another user to the organization - the email of the user that created the organization & assumed it is the organization created by the user with the email.

2022-06-14 16:00 UTC, andyjrII commented on src/organisation/organisation.controller.ts
> +  }
When I input the organization id, it is returning a 400 error 
![image](https://user-images.githubusercontent.com/102556498/173623053-45eb9503-c138-4d00-ba44-c87a5b36a964.png)

2022-06-14 16:41 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
Have you pulled the new changes?

2022-06-14 16:45 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
First, create a profile, then use the profile id as a parameter in ur url to create a new organization
A new organization will be created as also a role as admin in the profile-org table in reference to the profileId

2022-06-14 16:46 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
Also when adding a user, ensure the user already has a profile, otherwise you'll get an error

2022-06-14 16:47 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
Only admin can add new users now

2022-06-14 16:49 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
No, you can't add users twice, test again to confirm

2022-06-14 16:51 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  }
Fixed

2022-06-15 08:17 UTC, andyjrII commented on src/organisation/organisation.controller.ts
> +  }
Works fine now

2022-06-15 08:17 UTC, andyjrII approved these changes

2022-06-17 10:09 UTC, merged