categories
Zummit-Africa-Inc/zapi-dummy-core pull request #21
Opened 2022-06-13 16:31 UTC by samson-favour

add changes to the category service

2022-06-14 13:20 UTC, Chimexx requested changes

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.controller.ts
> +  @ApiOperation({ summary: 'Get an array of al categories' })
Fix this typo

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.controller.ts
> +    return await this.categoryService.createCategory(categoryDto);
Use zapi response object

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.controller.ts
> +    return this.categoryService.getCategoryById(id);
Please Identify everywhere you need to use zapi response object

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.service.ts
> +    const categories = await this.categoryRepository.find({});
What is the curly braces doing here?

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.service.ts
> +      if (error.code === '22P02') {
What if the error code doesn't match 22P02?

2022-06-14 13:20 UTC, Chimexx commented on src/category/category.service.ts
> +        ZapiResponse.BadRequest(`Task with  this ID - ${id} not found`),
Please re write this logic, I expect you to take clues from existing codes in the repo, but you are not doing that. What exactly are you deleting here?

2022-06-14 13:20 UTC, Chimexx commented on src/category/dto/create.category.ts
> +
use @ApiProperty() decorator

2022-06-14 13:20 UTC, Chimexx commented on src/database/repository/category.repository.ts
> +      throw new BadRequestException(
Why are you doing this inside the repository file?

2022-06-20 15:51 UTC, DorcasOJ commented on src/category/category.service.ts
> +        ZapiResponse.BadRequest(`Task with  this ID - ${id} not found`),
I think you should follow the norms of creating repository file in the main branch

2022-06-20 15:53 UTC, DorcasOJ requested changes
Kindly fix the requested changes

2022-06-27 16:05 UTC, closed without merging