Created endpoints module
Zummit-Africa-Inc/zapi-dummy-core pull request #27
Opened 2022-06-20 13:48 UTC by Chimexx

-Added endpoints module
-Removed error object from try-catch
-Changed some columns in endpoints entity to enum
-Removed endpointsId from Api entity

2022-06-20 16:07 UTC, DorcasOJ commented on src/endpoints/endpoints.service.ts
> +        ZapiResponse.BadRequest('Server error', '500 Internal Server Error'),
ZapiResponse.BadRequest('Server error', error, '500'),

2022-06-20 17:23 UTC, Chimexx commented on src/endpoints/endpoints.service.ts
> +        ZapiResponse.BadRequest('Server error', '500 Internal Server Error'),
It was so Initially, but brain doesn't want the whole error object showing up on the frontend...

2022-06-21 07:21 UTC, PhilemonBrain commented on src/endpoints/endpoints.service.ts
> +        ZapiResponse.BadRequest('Server error', '500 Internal Server Error'),
u can look at the error response and return only the message or a non sensitive info. All that info isn't really necessary

2022-06-21 07:29 UTC, PhilemonBrain requested changes

2022-06-21 07:29 UTC, PhilemonBrain commented on src/entities/api.entity.ts
>    @JoinColumn({ name: 'tutorialsId' })
is it possible to have this JoinColumn, without a relationship

2022-06-21 11:12 UTC, Chimexx commented
- Fixed error response
- removed relationship between tutorials and Api
- Updated migrations

2022-06-21 11:13 UTC, Chimexx commented
@PhilemonBrain  is the update okay?

2022-06-21 14:51 UTC, PhilemonBrain requested changes

2022-06-21 14:51 UTC, PhilemonBrain commented on src/entities/api.entity.ts
>    @JoinColumn({ name: 'discussionsId' })
please look at this. 
https://orkhan.gitbook.io/typeorm/docs/relations#joincolumn-options
i dont think u can use JoionColumn without a relationoship

2022-06-21 14:51 UTC, PhilemonBrain commented on src/api/api.service.ts
> +          error instanceof Error
i think u can just say error.message for now

2022-06-21 14:51 UTC, PhilemonBrain commented on src/api/api.service.ts
> +          error instanceof Error
and also it's replicated in numerous places, ignore that for now. But in the production level app, we wont leave it like this

2022-06-22 13:06 UTC, merged