Org branch 2
Zummit-Africa-Inc/zapi-dummy-core pull request #29
Opened 2022-06-21 19:24 UTC by DorcasOJ

- created an endpoint to update an existing organisation
- created an endpoint to delete an existing organisation and its users
- created an endpoint to delete a user from organisation
- create an endpoint to get all organisations

2022-06-22 08:56 UTC, Chimexx requested changes
Generally you can move some of the functions in service to utility folder, the file is too long.

2022-06-22 08:56 UTC, Chimexx commented on src/organisation/organisation.service.ts
> +    });
What if user.role === orgRole.ADMIN what happens?

2022-06-22 10:13 UTC, DorcasOJ commented on src/organisation/organisation.controller.ts
> +  @Delete('/:profileId/deleteUser/:id/:userEmail')
Okay

2022-06-22 10:30 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
> +    });
It continues.
user.role is an enum, if it's not orgRole.ADMIN then it's orgRole.DEVELOPER.

2022-06-22 12:32 UTC, PhilemonBrain requested changes
There are a couple of bugs in this code asides the one i pointed out. That's why i specifically requested only short code reviews. You need the fix these ones and drop some of the endpoints you have here. 

I noticed you also had helper functions, which is good practice but the code becomes tougher to review for ur colleagues. And u end up making more mistakes

So you need to trim down the endpoints for review. ASAP @DorcasOJ

2022-06-23 11:15 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
>        return await this.orgRepo.findOne(id);
the catch is in line 168-172

2022-06-23 11:19 UTC, DorcasOJ commented on src/organisation/organisation.service.ts
>        return await this.orgRepo.find();
the catch is in line 199-203

2022-06-23 13:04 UTC, DorcasOJ commented
Two endpoints were removed
-updateOrganisation
-deleteOneUser

2022-06-26 18:39 UTC, andyjrII approved these changes

2022-06-27 12:43 UTC, Chimexx approved these changes

2022-06-27 16:04 UTC, PhilemonBrain approved these changes

2022-06-27 16:05 UTC, merged