Endpoints for profile creation was generated
Zummit-Africa-Inc/zapi-dummy-core pull request #30
Opened 2022-06-24 10:39 UTC by SunmadeBabafemi

1. the following were generated for the profile endpoints..
    a. profile module
    b. profile service
    c. profile controller
    d. create-profile dto
2. endpoints were created to create a new profile and to fetch a single profile of a user.....

@DorcasOJ @andyjrII kindly review for merging

2022-06-25 12:48 UTC, PhilemonBrain requested changes

2022-06-25 12:48 UTC, PhilemonBrain commented on src/categories/category.controller.ts
>  import { CategoryService } from './category.service';
the changes you made in this file are fine, but you should have asked the person who worked on the file to do so.
@SunmadeBabafemi

2022-06-25 12:48 UTC, PhilemonBrain commented on src/profile/profile.controller.ts
> +import { Body, Controller, Get, Param, ParseUUIDPipe, Post } from '@nestjs/common';
you added api documentation to another persons code but forgot to do the same to yours. @SunmadeBabafemi

2022-06-25 12:48 UTC, PhilemonBrain commented on src/profile/profile.service.ts
> +            const profile = await this.profileRepo.create({
lines 22-26 aren't necessary. you could simply return await this.profileRepo.save({...profileDto})

2022-06-25 12:48 UTC, PhilemonBrain commented on src/profile/profile.service.ts
> +        if(!profile){
should we be throwing an error is something isn't available?? I just thinking if implementing this get methods d way repository classes implement theirs might be better. returning undefined instead of throwing an error

2022-06-25 19:10 UTC, SunmadeBabafemi commented on src/categories/category.controller.ts
>  import { CategoryService } from './category.service';
apologies sir.. i figured Korede was not available at the moment that was why....

2022-06-25 19:14 UTC, SunmadeBabafemi commented on src/profile/profile.controller.ts
> +import { Body, Controller, Get, Param, ParseUUIDPipe, Post } from '@nestjs/common';
yes sir.. the profile should not be created manually from the core service but automatically from the identity service with the axios request that was why i did not put the api documentation on them.... the user should not be creating a profile manually.. once the user signs up from the identity service, a profile entityl should be automatically generated during signup....

2022-06-27 07:12 UTC, PhilemonBrain approved these changes

2022-06-27 07:12 UTC, merged