Verify subscription of a user to an api before allowing his or her request
Zummit-Africa-Inc/zapi-dummy-core pull request #39
Opened 2022-07-06 05:08 UTC by SunmadeBabafemi

1. a verifySub method was created in the subscription.service.ts file
2. the respective endpoint for this was created in the subscription.controller.ts file
3. this takes the token generated during the user's subscription and verifies the token validity
4. then decodes the token and checks if the user making the request to an api is subscribed to the api.

NB: i feel this token should be stored in the subscription table of the database since it will be called upon every request the user makes to the api.

@Chimexx @andyjrII kindly review for merging.. thanks

2022-07-06 07:01 UTC, Chimexx requested changes
Generally good, look into the lines I commented

2022-07-06 07:58 UTC, SunmadeBabafemi commented on src/subscription/subscription.service.ts
> +    // const userRequest = await this.httpService.axiosRef.post('request url', {data: 'something'})
probably thinking the user making a call to the api's endpoint will pass through this verifySub.. but it can be removed... thanks

2022-07-06 08:06 UTC, SunmadeBabafemi commented on src/subscription/subscription.service.ts
> +        return ['user is subscribed to this API, in production this would return the request made by the user']
changes made

2022-07-14 21:11 UTC, PhilemonBrain commented
@SunmadeBabafemi please close this pr if its not necessary again

2022-07-15 11:32 UTC, closed without merging