Tutorial
Zummit-Africa-Inc/zapi-dummy-core pull request #41
Opened 2022-07-06 14:04 UTC by alahirajeffrey

This branch contains endpoints that can
- create a plain text tutorial
- delete a tutorial by id
- update a tutorial by id
- read a tutorial by id

2022-07-08 09:12 UTC, andyjrII approved these changes

2022-07-11 15:22 UTC, DorcasOJ commented on src/tutorial/dto/create-tutorial-dto.ts
> +    apiId: string
- maybe you can add apiId as a param instead

2022-07-11 15:27 UTC, DorcasOJ requested changes

2022-07-11 15:27 UTC, DorcasOJ commented on src/tutorial/dto/create-tutorial-dto.ts
> +    apiId: string
you can add apiId as a param instead

2022-07-11 19:10 UTC, alahirajeffrey commented on src/tutorial/dto/create-tutorial-dto.ts
> +    apiId: string
Alright will do that. Can you please explain why it is preferable that way. Thanks

2022-07-13 14:24 UTC, closed without merging