created security features for api
Zummit-Africa-Inc/zapi-dummy-core pull request #51
Opened 2022-07-21 19:34 UTC by johnayinde

added  secret key to Api  a UUID string to protect the api from being accessed by an unauthorized user
"Api-Secret-Key" is added on every request made to the api with the secret key as value

2022-07-21 21:58 UTC, PhilemonBrain requested changes

2022-07-21 21:58 UTC, PhilemonBrain commented on src/subscription/subscription.service.ts
> +    if (api.secretKey != uniqueApiSecurityKey) {
this unique api key is not for us. It's meant to be attached to the headers only

2022-07-21 21:58 UTC, PhilemonBrain commented on src/entities/api.entity.ts
> +  @Column()
there is no migration file for these changes on the entity schema.

2022-07-21 21:58 UTC, PhilemonBrain commented on src/entities/api.entity.ts
> +
What will happen to already existing entities when u add this changes

2022-07-21 21:58 UTC, PhilemonBrain commented on src/subscription/subscription.controller.ts
> +    const uniqueApiSecurityKey = request.headers['api-secret-key'];
there wont be such a header in this request and change the header name to X-ZAPI-Proxy-Secret

2022-07-22 12:18 UTC, johnayinde commented
New changes has been made 
Migration file generated and request header is sent on ever request made to an api

2022-07-22 18:59 UTC, PhilemonBrain requested changes

2022-07-22 18:59 UTC, PhilemonBrain commented on src/database/1658490667193-migration.ts
> +export class migration1658490667193 implements MigrationInterface {
@johnayinde this migration is wrong

2022-07-22 18:59 UTC, PhilemonBrain commented on src/database/1658490667193-migration.ts
> +export class migration1658490667193 implements MigrationInterface {
do u understand migrations?

2022-07-22 19:04 UTC, johnayinde commented on src/database/1658490667193-migration.ts
> +export class migration1658490667193 implements MigrationInterface {
@PhilemonBrain 
I don’t really understand it that well

 I went through the Typeorm doc and saw the same script command on the package.json file to generate the migration file **add-migration**

2022-07-24 14:55 UTC, PhilemonBrain commented on src/database/1658490667193-migration.ts
> +export class migration1658490667193 implements MigrationInterface {
@johnayinde  see if u can schedule a meet with @SunmadeBabafemi or @andyjrII to put u through

2022-07-26 14:42 UTC, PhilemonBrain approved these changes

2022-07-26 14:42 UTC, merged