feat: completed Id-Check-Guard
Zummit-Africa-Inc/zapi-dummy-core pull request #59
Opened 2022-08-03 09:51 UTC by Oladimejiibitoye

2022-08-03 11:48 UTC, Chimexx requested changes
Fix your conflicts too

2022-08-03 11:48 UTC, Chimexx commented on src/api/api.controller.ts
> +  @UseGuards(IdCheckGuard)
Instead of adding the guard on every route, why don't you call it once on the controller class, and it covers all routes. Or you can use global guard if you want to cover many parts of the app

2022-08-03 11:48 UTC, Chimexx commented on src/common/guards/idcheck.guard.ts
> +    console.log(Object.values(params));
Remove console.log

2022-08-03 11:59 UTC, Oladimejiibitoye commented on src/api/api.controller.ts
> +  @UseGuards(IdCheckGuard)
Noted, I would update

2022-08-03 11:59 UTC, Oladimejiibitoye commented on src/common/guards/idcheck.guard.ts
> +    console.log(Object.values(params));
whoos, I would update

2022-08-03 12:50 UTC, Chimexx commented
![Capture](https://user-images.githubusercontent.com/84224449/182611904-4ec0433d-0ece-4e34-ad0b-d4b534b67993.PNG)

Also fix the message and errorCode to match

2022-08-03 15:31 UTC, DorcasOJ commented on src/api/api.controller.ts
> +  @UseGuards(IdCheckGuard)
1. Yes please do

2022-08-03 15:31 UTC, DorcasOJ commented on src/api/api.controller.ts
> +  @UseGuards(IdCheckGuard)
Yes please do

2022-08-03 21:45 UTC, Jude-adesulu commented
You can just remove remove the package-json file . We don't add it to the PR cause it gives dependencies  version issues

2022-08-03 22:07 UTC, Jude-adesulu requested changes
Remove the package-lock.json file, it give issues while installing dependencies due to change in version. Also fix package.json conflict

2022-08-05 08:48 UTC, Chimexx approved these changes

2022-08-16 06:09 UTC, Chimexx requested changes
The server crashes if I try to query with a wrong Id 
I don't know if you tested the code, you should try it.

![Annotation 2022-08-16 070427](https://user-images.githubusercontent.com/84224449/184809449-47333bee-43d2-4776-8301-db5d010e0c83.png)

2022-08-16 06:09 UTC, Chimexx commented on src/api/api.controller.ts
> +  @IdCheck('apiId')
Do you have to call the decorator on every endpoint? I thought we you are aware of this

2022-08-16 06:16 UTC, Chimexx commented on src/common/guards/idcheck.guard.ts
> +//   'id': ProfileService
Remove this

2022-08-16 06:16 UTC, Chimexx commented on src/common/guards/idcheck.guard.ts
> +    console.log(requiredId);
Remove this

2022-08-16 08:40 UTC, Oladimejiibitoye commented on src/api/api.controller.ts
> +  @IdCheck('apiId')
1. I would fix the bug. 
2. The guard is declared globally but the @setmetadata has to be called on each endpoint because of its uniqueness. It has to be called on only endpoints with params.

2022-08-16 08:41 UTC, Oladimejiibitoye commented on src/common/guards/idcheck.guard.ts
> +//   'id': ProfileService
Noted

2022-08-16 08:41 UTC, Oladimejiibitoye commented on src/common/guards/idcheck.guard.ts
> +    console.log(requiredId);
Noted

2022-08-16 08:44 UTC, Chimexx commented on src/api/api.controller.ts
> +  @IdCheck('apiId')
Okay

2022-08-16 09:15 UTC, merged