Fixed issue with duplicate method
Zummit-Africa-Inc/zapi-dummy-core pull request #61
Opened 2022-08-10 21:35 UTC by TijanAyo

2022-08-11 06:11 UTC, Chimexx requested changes

2022-08-11 06:11 UTC, Chimexx commented on src/endpoints/endpoints.service.ts
> +        }
I think there is a possibility of two or more endpoints having the exact same method and route name (when they belong to different apis) . So you should narrow it down further using the apiId

2022-08-11 06:33 UTC, TijanAyo commented on src/endpoints/endpoints.service.ts
> +        }
That is what I tried narrowing down... once the user creates a route that has the same method... it should prompt out an error

2022-08-16 08:16 UTC, Chimexx approved these changes

2022-08-16 08:16 UTC, Chimexx commented on src/endpoints/endpoints.service.ts
> +            'An endpoint with duplicate method already exists, use another method',
Will be nice if you leave this as 'This endpoint already exists'

2022-08-16 08:20 UTC, TijanAyo commented on src/endpoints/endpoints.service.ts
> +            'An endpoint with duplicate method already exists, use another method',
I will do that...

2022-08-16 09:14 UTC, merged